# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Coffe Curators' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Coffe Curators

     pod 'Firebase/Firestore'
     pod 'FirebaseFirestoreSwift'
     pod 'Firebase/Auth'
     pod 'GoogleSignIn'
     pod 'Firebase/Analytics'
     pod 'StepIndicator', '~> 1.0.8'
     pod 'XLPagerTabStrip', '~> 9.0'

  target 'Coffe CuratorsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Coffe CuratorsUITests' do
    # Pods for testing
  end

end
